### ISSUE TITLE
Combining `list_align: new_line` and `long_list_align: multiline` causes spurious parenthesis for basic imports

### ISSUE THREAD

**Issue by mtkennerly** [jaspervdj/stylish-haskell#185]
With stylish-haskell 0.8.1.0, given this input:

```yaml
# .stylish-haskell.yaml
steps:
  - imports:
      list_align: new_line
      long_list_align: multiline
```

```haskell
module Demo where

import Control.Applicative
```

It produces this output with an incorrect closing parenthesis:

```haskell
module Demo where

import           Control.Applicative
    )
```
